# Generated by Django 4.2.16 on 2024-09-21 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=500)),
                ('product_features', models.CharField(max_length=5000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability_status', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
